version: '3.9'

services:
  kafka:
    image: confluentinc/cp-kafka:7.9.0
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "9999:9999"
    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk1234
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      
      KAFKA_LISTENERS: SASL_PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_PLAINTEXT:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_SUPER_USERS: User:admin
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
    volumes:
      - ./data:/var/lib/kafka/data
      - ./config/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
      - ./config/kraft.properties:/etc/kafka/kraft.properties
    command: >
      bash -c "if [ ! -f /var/lib/kafka/data/meta.properties ]; then
        echo 'Formatting storage...';
        kafka-storage format --ignore-formatted --cluster-id=${CLUSTER_ID} --config /etc/kafka/kraft.properties;
      fi && /etc/confluent/docker/run"
    networks:
      - net-db
networks:
  net-db:
    name: net-db
    driver: bridge
